### ISSUE TITLE
This fails in Beta2 - FYI

### ISSUE THREAD

**Issue by Waxhaw** [jmousseau/RoomObjectReplicatorDemo#1]
This isn't a shocker.  Just a comment in case anyone else is running Xcode 14 and iOS 16 beta 2.

The following categories are now missing:

- unknown
- washer
- screen

I set 'unknown' to 'storage', 'washer' to 'dishwasher' and 'screen' to 'television'.

Everything builds and runs now with no issues...   FYI

**Comment by jmousseau** [comment]
Ed,

Thanks for reporting the issue. Has been fixed in https://github.com/jmousseau/RoomObjectReplicator/commit/a1c6a1ea936849f56e90f986c84af9df1b1351fe.

**Comment by Waxhaw** [comment]
Nice!  Thanks for the quick fix.

Cheers
