### ISSUE TITLE
May you present a demo for walls doors windows custom usage?

### ISSUE THREAD

**Issue by jxhno1** [jmousseau/RoomObjectReplicatorDemo#2]

**Comment by jmousseau** [comment]
Apologies for the delayed response. Walls and doors can be visualized using the exact same pattern used for `CapturedRoom.Object` instances. Specifically, you'll

1. Update room object replicator to accept `CapturedRoom.Surface` instances.
2. Map these surfaces to a new `RoomSurfaceAnchor` `ARAnchor` subclasses.
3. For each `RoomSurfaceAnchor`  in the session, create a new `RoomSurfaceEntity`, which can have a model component to visualize the surface.
